/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'country' : string,
  'city' : string,
  'zipCode' : string,
  'state' : string,
}
export interface Contact {
  'relationship' : string,
  'name' : string,
  'phone' : string,
}
export interface EmployeeDetails {
  'designation' : string,
  'joiningDate' : Time,
  'businessEmail' : string,
  'emergencyContacts' : Array<Contact>,
  'employmentType' : string,
  'address' : Address,
  'department' : string,
  'phoneNumber' : string,
}
export interface EmployeeProfile {
  'internalId' : bigint,
  'status' : string,
  'personalEmail' : [] | [string],
  'role' : EmployeeRole,
  'joiningDate' : Time,
  'businessEmail' : string,
  'department' : string,
  'phoneNumber' : string,
}
export interface EmployeeRecord {
  'internalId' : bigint,
  'status' : string,
  'leaveBalance' : LeaveBalance,
  'personalEmail' : [] | [string],
  'designation' : string,
  'role' : EmployeeRole,
  'joiningDate' : Time,
  'businessEmail' : string,
  'employmentType' : string,
  'employeeId' : string,
  'department' : string,
  'phoneNumber' : string,
}
export type EmployeeRole = { 'hrManager' : null } |
  { 'manager' : null } |
  { 'superAdmin' : null } |
  { 'employee' : null } |
  { 'hrStaff' : null };
export type ExternalBlob = Uint8Array;
export interface LeaveBalance {
  'sick' : bigint,
  'annual' : bigint,
  'unpaid' : bigint,
  'casual' : bigint,
}
export interface LeaveRequest {
  'status' : string,
  'requestId' : bigint,
  'endDate' : Time,
  'employeeId' : string,
  'leaveType' : string,
  'startDate' : Time,
}
export interface Letter {
  'created' : Time,
  'createdBy' : Principal,
  'letterType' : string,
  'employeeId' : string,
  'document' : ExternalBlob,
  'letterId' : bigint,
}
export interface Payslip {
  'month' : string,
  'payslipId' : bigint,
  'year' : string,
  'payslipDocument' : ExternalBlob,
  'employeeId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : EmployeeRole,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveLeaveRequest' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmployee' : ActorMethod<[EmployeeDetails], string>,
  'generateLetter' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<EmployeeProfile>>,
  'getAllEmployeesByJoiningDate' : ActorMethod<[], Array<EmployeeProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], EmployeeProfile>,
  'getEmployeeRecords' : ActorMethod<[], Array<EmployeeRecord>>,
  'getLeaveBalance' : ActorMethod<[string], LeaveBalance>,
  'getLeaveRequests' : ActorMethod<[string], Array<LeaveRequest>>,
  'getLetters' : ActorMethod<[string], Array<Letter>>,
  'getPayslips' : ActorMethod<[string], Array<Payslip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerNewEmployee' : ActorMethod<[EmployeeProfile], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeaveRequest' : ActorMethod<[string, string, Time, Time], bigint>,
  'uploadPayslip' : ActorMethod<[string, string, string, ExternalBlob], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];