/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Contact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
});
export const EmployeeDetails = IDL.Record({
  'designation' : IDL.Text,
  'joiningDate' : Time,
  'businessEmail' : IDL.Text,
  'emergencyContacts' : IDL.Vec(Contact),
  'employmentType' : IDL.Text,
  'address' : Address,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EmployeeRole = IDL.Variant({
  'hrManager' : IDL.Null,
  'manager' : IDL.Null,
  'superAdmin' : IDL.Null,
  'employee' : IDL.Null,
  'hrStaff' : IDL.Null,
});
export const EmployeeProfile = IDL.Record({
  'internalId' : IDL.Nat,
  'status' : IDL.Text,
  'personalEmail' : IDL.Opt(IDL.Text),
  'role' : EmployeeRole,
  'joiningDate' : Time,
  'businessEmail' : IDL.Text,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : EmployeeRole,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const LeaveBalance = IDL.Record({
  'sick' : IDL.Nat,
  'annual' : IDL.Nat,
  'unpaid' : IDL.Nat,
  'casual' : IDL.Nat,
});
export const EmployeeRecord = IDL.Record({
  'internalId' : IDL.Nat,
  'status' : IDL.Text,
  'leaveBalance' : LeaveBalance,
  'personalEmail' : IDL.Opt(IDL.Text),
  'designation' : IDL.Text,
  'role' : EmployeeRole,
  'joiningDate' : Time,
  'businessEmail' : IDL.Text,
  'employmentType' : IDL.Text,
  'employeeId' : IDL.Text,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const LeaveRequest = IDL.Record({
  'status' : IDL.Text,
  'requestId' : IDL.Nat,
  'endDate' : Time,
  'employeeId' : IDL.Text,
  'leaveType' : IDL.Text,
  'startDate' : Time,
});
export const Letter = IDL.Record({
  'created' : Time,
  'createdBy' : IDL.Principal,
  'letterType' : IDL.Text,
  'employeeId' : IDL.Text,
  'document' : ExternalBlob,
  'letterId' : IDL.Nat,
});
export const Payslip = IDL.Record({
  'month' : IDL.Text,
  'payslipId' : IDL.Nat,
  'year' : IDL.Text,
  'payslipDocument' : ExternalBlob,
  'employeeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveLeaveRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmployee' : IDL.Func([EmployeeDetails], [IDL.Text], []),
  'generateLetter' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(EmployeeProfile)], ['query']),
  'getAllEmployeesByJoiningDate' : IDL.Func(
      [],
      [IDL.Vec(EmployeeProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [EmployeeProfile], ['query']),
  'getEmployeeRecords' : IDL.Func([], [IDL.Vec(EmployeeRecord)], ['query']),
  'getLeaveBalance' : IDL.Func([IDL.Text], [LeaveBalance], ['query']),
  'getLeaveRequests' : IDL.Func([IDL.Text], [IDL.Vec(LeaveRequest)], ['query']),
  'getLetters' : IDL.Func([IDL.Text], [IDL.Vec(Letter)], ['query']),
  'getPayslips' : IDL.Func([IDL.Text], [IDL.Vec(Payslip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerNewEmployee' : IDL.Func([EmployeeProfile], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeaveRequest' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time],
      [IDL.Nat],
      [],
    ),
  'uploadPayslip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const EmployeeDetails = IDL.Record({
    'designation' : IDL.Text,
    'joiningDate' : Time,
    'businessEmail' : IDL.Text,
    'emergencyContacts' : IDL.Vec(Contact),
    'employmentType' : IDL.Text,
    'address' : Address,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EmployeeRole = IDL.Variant({
    'hrManager' : IDL.Null,
    'manager' : IDL.Null,
    'superAdmin' : IDL.Null,
    'employee' : IDL.Null,
    'hrStaff' : IDL.Null,
  });
  const EmployeeProfile = IDL.Record({
    'internalId' : IDL.Nat,
    'status' : IDL.Text,
    'personalEmail' : IDL.Opt(IDL.Text),
    'role' : EmployeeRole,
    'joiningDate' : Time,
    'businessEmail' : IDL.Text,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : EmployeeRole,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const LeaveBalance = IDL.Record({
    'sick' : IDL.Nat,
    'annual' : IDL.Nat,
    'unpaid' : IDL.Nat,
    'casual' : IDL.Nat,
  });
  const EmployeeRecord = IDL.Record({
    'internalId' : IDL.Nat,
    'status' : IDL.Text,
    'leaveBalance' : LeaveBalance,
    'personalEmail' : IDL.Opt(IDL.Text),
    'designation' : IDL.Text,
    'role' : EmployeeRole,
    'joiningDate' : Time,
    'businessEmail' : IDL.Text,
    'employmentType' : IDL.Text,
    'employeeId' : IDL.Text,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const LeaveRequest = IDL.Record({
    'status' : IDL.Text,
    'requestId' : IDL.Nat,
    'endDate' : Time,
    'employeeId' : IDL.Text,
    'leaveType' : IDL.Text,
    'startDate' : Time,
  });
  const Letter = IDL.Record({
    'created' : Time,
    'createdBy' : IDL.Principal,
    'letterType' : IDL.Text,
    'employeeId' : IDL.Text,
    'document' : ExternalBlob,
    'letterId' : IDL.Nat,
  });
  const Payslip = IDL.Record({
    'month' : IDL.Text,
    'payslipId' : IDL.Nat,
    'year' : IDL.Text,
    'payslipDocument' : ExternalBlob,
    'employeeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveLeaveRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmployee' : IDL.Func([EmployeeDetails], [IDL.Text], []),
    'generateLetter' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(EmployeeProfile)], ['query']),
    'getAllEmployeesByJoiningDate' : IDL.Func(
        [],
        [IDL.Vec(EmployeeProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [EmployeeProfile], ['query']),
    'getEmployeeRecords' : IDL.Func([], [IDL.Vec(EmployeeRecord)], ['query']),
    'getLeaveBalance' : IDL.Func([IDL.Text], [LeaveBalance], ['query']),
    'getLeaveRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getLetters' : IDL.Func([IDL.Text], [IDL.Vec(Letter)], ['query']),
    'getPayslips' : IDL.Func([IDL.Text], [IDL.Vec(Payslip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerNewEmployee' : IDL.Func([EmployeeProfile], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeaveRequest' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time],
        [IDL.Nat],
        [],
      ),
    'uploadPayslip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };