/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Payslip {
    month: string;
    payslipId: bigint;
    year: string;
    payslipDocument: ExternalBlob;
    employeeId: string;
}
export interface Letter {
    created: Time;
    createdBy: Principal;
    letterType: string;
    employeeId: string;
    document: ExternalBlob;
    letterId: bigint;
}
export type Time = bigint;
export interface Address {
    street: string;
    country: string;
    city: string;
    zipCode: string;
    state: string;
}
export interface Contact {
    relationship: string;
    name: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LeaveRequest {
    status: string;
    requestId: bigint;
    endDate: Time;
    employeeId: string;
    leaveType: string;
    startDate: Time;
}
export interface EmployeeRecord {
    internalId: bigint;
    status: string;
    leaveBalance: LeaveBalance;
    personalEmail?: string;
    designation: string;
    role: EmployeeRole;
    joiningDate: Time;
    businessEmail: string;
    employmentType: string;
    employeeId: string;
    department: string;
    phoneNumber: string;
}
export interface EmployeeProfile {
    internalId: bigint;
    status: string;
    personalEmail?: string;
    role: EmployeeRole;
    joiningDate: Time;
    businessEmail: string;
    department: string;
    phoneNumber: string;
}
export interface EmployeeDetails {
    designation: string;
    joiningDate: Time;
    businessEmail: string;
    emergencyContacts: Array<Contact>;
    employmentType: string;
    address: Address;
    department: string;
    phoneNumber: string;
}
export interface LeaveBalance {
    sick: bigint;
    annual: bigint;
    unpaid: bigint;
    casual: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: EmployeeRole;
    employeeId?: string;
}
export enum EmployeeRole {
    hrManager = "hrManager",
    manager = "manager",
    superAdmin = "superAdmin",
    employee = "employee",
    hrStaff = "hrStaff"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveLeaveRequest(employeeId: string, requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEmployee(details: EmployeeDetails): Promise<string>;
    generateLetter(employeeId: string, letterType: string, blobReference: ExternalBlob): Promise<void>;
    getAllEmployees(): Promise<Array<EmployeeProfile>>;
    getAllEmployeesByJoiningDate(): Promise<Array<EmployeeProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(employeeId: string): Promise<EmployeeProfile>;
    getEmployeeRecords(): Promise<Array<EmployeeRecord>>;
    getLeaveBalance(employeeId: string): Promise<LeaveBalance>;
    getLeaveRequests(employeeId: string): Promise<Array<LeaveRequest>>;
    getLetters(employeeId: string): Promise<Array<Letter>>;
    getPayslips(employeeId: string): Promise<Array<Payslip>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerNewEmployee(profile: EmployeeProfile): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitLeaveRequest(employeeId: string, leaveType: string, startDate: Time, endDate: Time): Promise<bigint>;
    uploadPayslip(employeeId: string, month: string, year: string, blobReference: ExternalBlob): Promise<bigint>;
}
import type { EmployeeProfile as _EmployeeProfile, EmployeeRecord as _EmployeeRecord, EmployeeRole as _EmployeeRole, ExternalBlob as _ExternalBlob, LeaveBalance as _LeaveBalance, Letter as _Letter, Payslip as _Payslip, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveLeaveRequest(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEmployee(arg0: EmployeeDetails): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0);
            return result;
        }
    }
    async generateLetter(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLetter(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLetter(arg0, arg1, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployeesByJoiningDate(): Promise<Array<EmployeeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeesByJoiningDate();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeesByJoiningDate();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: string): Promise<EmployeeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_EmployeeProfile_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_EmployeeProfile_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeRecords(): Promise<Array<EmployeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeRecords();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeRecords();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveBalance(arg0: string): Promise<LeaveBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalance(arg0);
            return result;
        }
    }
    async getLeaveRequests(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequests(arg0);
            return result;
        }
    }
    async getLetters(arg0: string): Promise<Array<Letter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetters(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetters(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayslips(arg0: string): Promise<Array<Payslip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayslips(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayslips(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerNewEmployee(arg0: EmployeeProfile): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNewEmployee(to_candid_EmployeeProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNewEmployee(to_candid_EmployeeProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitLeaveRequest(arg0: string, arg1: string, arg2: Time, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadPayslip(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPayslip(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPayslip(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_EmployeeProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeProfile): EmployeeProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRecord): EmployeeRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Letter_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Letter): Promise<Letter> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Payslip_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payslip): Promise<Payslip> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internalId: bigint;
    status: string;
    personalEmail: [] | [string];
    role: _EmployeeRole;
    joiningDate: _Time;
    businessEmail: string;
    department: string;
    phoneNumber: string;
}): {
    internalId: bigint;
    status: string;
    personalEmail?: string;
    role: EmployeeRole;
    joiningDate: Time;
    businessEmail: string;
    department: string;
    phoneNumber: string;
} {
    return {
        internalId: value.internalId,
        status: value.status,
        personalEmail: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.personalEmail)),
        role: from_candid_EmployeeRole_n15(_uploadFile, _downloadFile, value.role),
        joiningDate: value.joiningDate,
        businessEmail: value.businessEmail,
        department: value.department,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _EmployeeRole;
    employeeId: [] | [string];
}): {
    name: string;
    role: EmployeeRole;
    employeeId?: string;
} {
    return {
        name: value.name,
        role: from_candid_EmployeeRole_n15(_uploadFile, _downloadFile, value.role),
        employeeId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internalId: bigint;
    status: string;
    leaveBalance: _LeaveBalance;
    personalEmail: [] | [string];
    designation: string;
    role: _EmployeeRole;
    joiningDate: _Time;
    businessEmail: string;
    employmentType: string;
    employeeId: string;
    department: string;
    phoneNumber: string;
}): {
    internalId: bigint;
    status: string;
    leaveBalance: LeaveBalance;
    personalEmail?: string;
    designation: string;
    role: EmployeeRole;
    joiningDate: Time;
    businessEmail: string;
    employmentType: string;
    employeeId: string;
    department: string;
    phoneNumber: string;
} {
    return {
        internalId: value.internalId,
        status: value.status,
        leaveBalance: value.leaveBalance,
        personalEmail: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.personalEmail)),
        designation: value.designation,
        role: from_candid_EmployeeRole_n15(_uploadFile, _downloadFile, value.role),
        joiningDate: value.joiningDate,
        businessEmail: value.businessEmail,
        employmentType: value.employmentType,
        employeeId: value.employeeId,
        department: value.department,
        phoneNumber: value.phoneNumber
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    createdBy: Principal;
    letterType: string;
    employeeId: string;
    document: _ExternalBlob;
    letterId: bigint;
}): Promise<{
    created: Time;
    createdBy: Principal;
    letterType: string;
    employeeId: string;
    document: ExternalBlob;
    letterId: bigint;
}> {
    return {
        created: value.created,
        createdBy: value.createdBy,
        letterType: value.letterType,
        employeeId: value.employeeId,
        document: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.document),
        letterId: value.letterId
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: string;
    payslipId: bigint;
    year: string;
    payslipDocument: _ExternalBlob;
    employeeId: string;
}): Promise<{
    month: string;
    payslipId: bigint;
    year: string;
    payslipDocument: ExternalBlob;
    employeeId: string;
}> {
    return {
        month: value.month,
        payslipId: value.payslipId,
        year: value.year,
        payslipDocument: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.payslipDocument),
        employeeId: value.employeeId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hrManager: null;
} | {
    manager: null;
} | {
    superAdmin: null;
} | {
    employee: null;
} | {
    hrStaff: null;
}): EmployeeRole {
    return "hrManager" in value ? EmployeeRole.hrManager : "manager" in value ? EmployeeRole.manager : "superAdmin" in value ? EmployeeRole.superAdmin : "employee" in value ? EmployeeRole.employee : "hrStaff" in value ? EmployeeRole.hrStaff : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeProfile>): Array<EmployeeProfile> {
    return value.map((x)=>from_candid_EmployeeProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeRecord>): Array<EmployeeRecord> {
    return value.map((x)=>from_candid_EmployeeRecord_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Letter>): Promise<Array<Letter>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Letter_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payslip>): Promise<Array<Payslip>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Payslip_n30(_uploadFile, _downloadFile, x)));
}
function to_candid_EmployeeProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeProfile): _EmployeeProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internalId: bigint;
    status: string;
    personalEmail?: string;
    role: EmployeeRole;
    joiningDate: Time;
    businessEmail: string;
    department: string;
    phoneNumber: string;
}): {
    internalId: bigint;
    status: string;
    personalEmail: [] | [string];
    role: _EmployeeRole;
    joiningDate: _Time;
    businessEmail: string;
    department: string;
    phoneNumber: string;
} {
    return {
        internalId: value.internalId,
        status: value.status,
        personalEmail: value.personalEmail ? candid_some(value.personalEmail) : candid_none(),
        role: to_candid_EmployeeRole_n34(_uploadFile, _downloadFile, value.role),
        joiningDate: value.joiningDate,
        businessEmail: value.businessEmail,
        department: value.department,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: EmployeeRole;
    employeeId?: string;
}): {
    name: string;
    role: _EmployeeRole;
    employeeId: [] | [string];
} {
    return {
        name: value.name,
        role: to_candid_EmployeeRole_n34(_uploadFile, _downloadFile, value.role),
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    hrManager: null;
} | {
    manager: null;
} | {
    superAdmin: null;
} | {
    employee: null;
} | {
    hrStaff: null;
} {
    return value == EmployeeRole.hrManager ? {
        hrManager: null
    } : value == EmployeeRole.manager ? {
        manager: null
    } : value == EmployeeRole.superAdmin ? {
        superAdmin: null
    } : value == EmployeeRole.employee ? {
        employee: null
    } : value == EmployeeRole.hrStaff ? {
        hrStaff: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
